# Generated by Django 3.0.4 on 2020-05-27 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
